### ISSUE TITLE
Did you plan to update to a newer Gradle version?

### ISSUE THREAD

**Issue by kuniss** [Ullink/gradle-nunit-plugin#38]
If so, to which one?
I have encountered some issues when using Gradle versions 2.13 and 2.14 (different issues for both versions) due to changed Gradle API. 
The 2.14 issue is related to a not available Logger class.
The 2.13 issue is related to deprecated "DefaultSourceDirectorySet(String, FileResolver)" call (as I remember).

**Comment by gluck** [comment]
Yes we should.
I released version 1.9 which should be compatible with gradle 2.14 (at least it was built and tests pass with it), it required some upgrades to dependencies, let me know if it works for you.
Next will be the upgrade/compatibility with gradle v3.

**Comment by kuniss** [comment]
Great! This works for me so far.

**Comment by kuniss** [comment]
The only thing I encountered is a JNA version mismatch which under circumstances let the build fail (but then regularly).
The error look something like that 

```
Execution failed for task ':prepare'.
 >
   There is an incompatible JNA native library installed on this system.
   To resolve this issue you may do one of the following:
    - remove or uninstall the offending library
    - set the system property jna.nosys=true
    - set jna.boot.library.path to include the path to the version of the
      jnidispatch library included with the JNA jar file you are using
```

Setting "jna.nosys=true" does not help always.

I guess, it comes from the very old JNA3 version contained in the Gradle 2.14 distribution.
Your msbuild plugin (I'm using too) is using JNA 4.2.+ as I saw. This will be the problem. But it's not your failure...
I guess, only upgrading your plugins to Gradle version 3.1 where the JNA library has been erased from distribution will solve this problem.
