### ISSUE TITLE
How to change the report name and destination.

### ISSUE THREAD

**Issue by g1ps** [Ullink/gradle-nunit-plugin#45]
The report currently goes to `\build\nunit\reports\TestResult.xml`. How do we change that?

I looked through the code. There appears to have been some intention to provide this but I can't see a way to do it. There's nothing in the docs. You have the string `TestResult.xml` hard-coded at least 6 times, which seems ridiculous. There are apparently unnecessary comparisons between `reportFileName ` and `DEFAULT_REPORT_FILE_NAME`, which are both hard-coded to that same string. This is about the most basic facility you'd expect the plugin to provide. Have I missed something?

Thanks.

**Comment by ngyukman** [comment]
hi @g1ps 

you can specify the report location by

```groovy
nunit {
  reportFolder = file('some/where/')
  reportFileName = 'foo.xml'
}
```

the file you were looking at is a gradle extension class, which is for providing an extension for user to override them in build.gradle

**Comment by g1ps** [comment]
OK, thanks. That worked. How would we know that? At the very least they should be documented on the front page here. Are there any others that would be useful to know?

Thanks again.

**Comment by ngyukman** [comment]
Thanks with your suggestion
