### ISSUE TITLE
Continue on failure

### ISSUE THREAD

**Issue by g1ps** [Ullink/gradle-nunit-plugin#46]
How do I prevent the plugin from failing the entire Gradle build when tests fail? I want to be able to process the results and do other work before the build finishes but that doesn't currently seem possible. The only option I see is to set `ignoreFailures = true` which does allow it to continue but has the undesirable effect of causing the build to return success, which it definitely shouldn't if tests have failed. I expect the plugin to return the failure somehow but it shouldn't kill the entire process. When Gradle completes it should report failure, it just shouldn't fail before I'm ready. 

I run the `nunit` task as a dependency of another in my build.

Thanks.

**Comment by gluck** [comment]
Hi,

this behavior is the same as the regular gradle [test task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:ignoreFailures).
It's unclear what you're trying the achieve, but the rationale for this token is to be used (`true`) on CI, as the CI server (e.g. jenkins) will process the test results file and will detect/report failures as part of the CI outcome. Returning a non-success error code is (usually) not desirable on CI, as it makes it look like the build failed, whereas is was a test failure.

If that's what you need, I don't think/know there's another way for you to have a non-success-exit-value except by failing the build, but that would be a Gradle question better fit for StackOverflow or Gradle forums.

If you want to run your task `B` which depends on `nunit` even if `nunit` fails, maybe have a look towards [task finalizers](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:finalizer_tasks), they run even if the linked task failed.

**Comment by g1ps** [comment]
Hi,

What you described is exactly what I'm after. I may have been overthinking things as I agree with you. I'll have an other look, perhaps I mistook something that was happening. Thanks for the pointer to finalizers, that's useful.

Cheers.
