### ISSUE TITLE
NUnit integration with C# Project

### ISSUE THREAD

**Issue by novabyte** [Ullink/gradle-nunit-plugin#9]
Fantastic work on these Gradle plugins for MS-related tools and libraries. I'm using the `msbuild` plugin to great effect on a soon to be open-source library for Unity.

I'd like to integrate NUnit tests with my project. I know the issue tracker is not a Q&A forum but I couldn't find a project (not even [rx-shim](https://github.com/Ullink/rx-shim)) as an example of how to setup my `.csproj` and make it work with this `nunit` plugin.

Is there an example you could share on how to configure `nunit` and use it with this plugin?

**Comment by gluck** [comment]
You can have a look at [ilrepack](https://github.com/gluck/il-repack) build as it uses nunit.

Let us know if you have any trouble, I can also offer to review your build.

**Comment by novabyte** [comment]
@gluck Thanks for the very fast response. The example project you linked to has everything I need to put together NUnit and the Gradle build plugins with my project.

I'd appreciate a quick review of my build setup when I have it wired up; I'll open an issue on my project and mention you when it's open-source on GitHub. Thanks.
